# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
$num_compute_nodes = 1

Vagrant.configure("2") do |config|

  config.vm.box = "yk0/ubuntu-xenial"

  config.vm.provision "shell", path: "setup_repo.sh", privileged: false
  config.vm.provision "shell", path: "setup_ovs_dpdk.sh", privileged: false
  config.vm.provision "shell", path: "bootstrap.sh", privileged: false

  config.vm.define "control" do |config|
    config.vm.hostname = "control"
    config.vm.network "private_network", ip: "192.168.0.10"
    config.vm.network :private_network,  ip: "192.168.1.10"
    config.vm.provision "shell", path: "setup_control.sh", privileged: false
    config.vm.provider :libvirt do |libvirt|
      libvirt.memory = 40960
      libvirt.cpus = 8
      libvirt.nested = true
    end
  end

  (1 .. $num_compute_nodes).each do |n|
    config.vm.define vm_name = "compute-#{n}" do |config|
      config.vm.hostname = vm_name
      config.vm.network "private_network", ip: "192.168.0.#{n+20}"
      config.vm.network :private_network,  ip: "192.168.1.#{n+20}"
      config.vm.provision "shell", path: "setup_compute.sh", privileged: false
      config.vm.provider :libvirt do |libvirt|
        libvirt.memory = 81920
        libvirt.cpus = 20
        libvirt.nested = true
      end
    end
  end
end
