apiVersion: v1
kind: Pod
metadata: 
    annotations:
    labels: 
        env: dev
        tie: front
    name: nginx1
    namespace: default
spec: 
    containers:
        - image: nginx:1.7.9
          name: nginx
          ports: 
              - containerPort: 80
                protocol: TCP
