apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  labels:
    app: busybox1
spec:
  containers:
  - name: busybox1
    image: busybox
    command: ['sh', '-c', 'sleep 100000']
  nodeSelector:
    host: worker1
