# kubectl create configmap special-config --from-literal=special.how=very
#      command: [ "/bin/sh", "-c", "env" ]
apiVersion: v1
kind: Pod
metadata: 
  name: cm-cmd-test
spec: 
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "echo $(SPECIAL_LEVEL_KEY)" ]
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef: 
              name: special-config
              key: special.how
  restartPolicy: Never
