apiVersion: v1
kind: Pod
metadata: 
  name: test-volume
spec: 
  containers:
  - name: test-volume
    image: ubuntu:18.04
    command: ["bin/sh"]
    args: ["-c", "sleep 3600 && echo Sleep expired > /dev/termination-log"]
    volumeMounts:
    - name: hostpath-volume
      mountPath: "/data"
      readOnly: true
  volumes:
    - name: hostpath-volume
      hostPath:
        path: /tmp/data
