sudo docker pull     docker.elastic.co/beats/filebeat:5.5.0
sudo docker pull     docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.3
sudo docker pull     docker.elastic.co/elasticsearch/elasticsearch:5.5.0
sudo docker pull     docker.elastic.co/elasticsearch/elasticsearch:6.1.2
sudo docker pull     docker.elastic.co/elasticsearch/elasticsearch:6.3.1
sudo docker pull     docker.elastic.co/kibana/kibana:5.5.0
sudo docker pull     docker.elastic.co/kibana/kibana:6.3.1
sudo docker pull     docker.elastic.co/logstash/logstash:5.4.3
sudo docker pull     docker.io/aaionap/haproxy:1.2.4
sudo docker pull     docker.io/wurstmeister/zookeeper:latest
sudo docker pull     registry.hub.docker.com/library/consul:0.9.3
sudo docker pull     alpine:3.6
#sudo docker pull     crunchydata/crunchy-pgpool:centos7-10.4-2.0 
sudo docker pull     crunchydata/crunchy-pgpool:centos7-10.4-2.0.0
sudo docker pull     docker.io/busybox
sudo docker pull     docker.io/library/busybox:latest
sudo docker pull     docker.io/nginx:1.13-alpine
sudo docker pull     docker.io/ninech/netbox:v2.3.5
sudo docker pull     docker.io/oomk8s/consul:1.0.0
sudo docker pull     docker.io/postgres:10.2-alpine
sudo docker pull     docker.io/taskrabbit/elasticsearch-dump
sudo docker pull     oomk8s/readiness-check:2.0.0
sudo docker pull     oomk8s/readiness-check:2.0.1
sudo docker pull     oomk8s/ubuntu-init:1.0.0
sudo docker pull     registry.hub.docker.com/library/busybox:latest
sudo docker pull     registry.hub.docker.com/oomk8s/ubuntu-init:2.0.0
#sudo docker pull     gcr.io/google_samples/k8szk:v3
#sudo docker pull     gcr.io/google-samples/xtrabackup:1.0
sudo docker pull     cassandra:2.1
sudo docker pull     docker.io/consul:1.0.6
sudo docker pull     crunchydata/crunchy-postgres:centos7-10.4-2.0.0
sudo docker pull     registry.hub.docker.com/library/mongo:3
sudo docker pull     registry.hub.docker.com/library/mysql:5.7
