#sudo docker pull      gcr.io/google_samples/k8szk:v3 &
#sudo docker pull     gcr.io/google-samples/xtrabackup:1.0 &
sudo docker pull       docker.elastic.co/beats/filebeat:5.5.0 &
sudo docker pull      cassandra:2.1 &
sudo docker pull      docker.io/consul:1.0.6 &
sudo docker pull      nexus3.onap.org:10001/adfinissygroup/k8s-mariadb-galera-centos:v002 &
sudo docker pull      nexus3.onap.org:10001/onap/appc-image:1.4.3 &
sudo docker pull      nexus3.onap.org:10001/onap/music/cassandra_3_11:3.0.24 &
sudo docker pull      nexus3.onap.org:10001/onap/org.onap.dcaegen2.deployments.redis-cluster-container:1.0.0 &
sudo docker pull      nexus3.onap.org:10001/onap/policy-drools:1.3.4 &
sudo docker pull      nexus3.onap.org:10001/onap/sdnc-image:1.4.3 &
sudo docker pull     crunchydata/crunchy-postgres:centos7-10.4-2.0.0 &
sudo docker pull     nexus3.onap.org:10001/busybox &
sudo docker pull     nexus3.onap.org:10001/library/consul:1.0.6 &
sudo docker pull     nexus3.onap.org:10001/library/vault:0.10.0 &
sudo docker pull     nexus3.onap.org:10001/onap/aaf/smsquorumclient:3.0.1 &
sudo docker pull     nexus3.onap.org:10001/onap/policy-apex-pdp:2.0.3 &
sudo docker pull     nexus3.onap.org:10001/onap/policy-pe:1.3.4 &
sudo docker pull     oomk8s/readiness-check:2.0.0 &
sudo docker pull     registry.hub.docker.com/library/busybox:latest &
sudo docker pull     registry.hub.docker.com/library/mongo:3 &
sudo docker pull     registry.hub.docker.com/library/mysql:5.7 &
